SELECT
  p.PRODUCT_CODE,
  SUM(o.SALES_AMOUNT) * p.PRICE AS PRICE
FROM 
  PRODUCT p
INNER JOIN 
  OFFLINE_SALE o ON o.PRODUCT_ID = p.PRODUCT_ID
GROUP BY
  o.PRODUCT_ID
ORDER BY
  PRICE DESC, PRODUCT_CODE ASC;
  