SELECT 
  YEAR(s.SALES_DATE) AS YEAR,
  MONTH(s.SALES_DATE) AS MONTH,
  u.GENDER,
  COUNT(DISTINCT s.USER_ID) AS USERS
FROM USER_INFO u
INNER JOIN ONLINE_SALE s 
  ON u.USER_ID = s.USER_ID
WHERE u.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, u.GENDER
ORDER BY YEAR, MONTH, u.GENDER