WITH joined_2021 AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
),
total_users AS (
    SELECT COUNT(*) AS total_cnt
    FROM joined_2021
)
SELECT 
    YEAR(os.SALES_DATE) AS YEAR,
    MONTH(os.SALES_DATE) AS MONTH,
    COUNT(DISTINCT os.USER_ID) AS PURCHASED_USERS,
    ROUND(
        COUNT(DISTINCT os.USER_ID) / t.total_cnt,
        1
    ) AS PURCHASE_RATIO
FROM ONLINE_SALE os
JOIN joined_2021 j 
    ON os.USER_ID = j.USER_ID
CROSS JOIN total_users t
GROUP BY YEAR(os.SALES_DATE), MONTH(os.SALES_DATE)
ORDER BY YEAR(os.SALES_DATE), MONTH(os.SALES_DATE);
