WITH RECURSIVE CTE AS (
  SELECT
    ID,
    PARENT_ID,
    1 AS GENERATION
  FROM ECOLI_DATA
  WHERE PARENT_ID IS NULL

  UNION ALL

  SELECT
    e.ID,
    e.PARENT_ID,
    c.GENERATION + 1 AS GENERATION
  FROM CTE AS c
  JOIN ECOLI_DATA AS e
    ON c.ID = e.PARENT_ID
)
SELECT
  COUNT(*) AS COUNT,
  GENERATION
FROM CTE
WHERE ID NOT IN (
  SELECT DISTINCT PARENT_ID
  FROM ECOLI_DATA
  WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION
ORDER BY GENERATION;
