SELECT 
  u.USER_ID,
  u.NICKNAME,
  SUM(b.PRICE) AS TOTAL_SALES
FROM 
  USED_GOODS_BOARD b
INNER JOIN
  USED_GOODS_USER u On u.USER_ID = b.WRITER_ID
WHERE 
  b.STATUS = 'DONE'
GROUP BY
  b.WRITER_ID
HAVING
  SUM(b.PRICE) >= 700000
ORDER BY
  TOTAL_SALES ASC
  