SELECT
  COUNT(*) AS FISH_COUNT,
  MAX(f.LENGTH) AS MAX_LENGTH,
  f.FISH_TYPE AS FISH_TYPE
FROM (
  SELECT
    FISH_TYPE,
    CASE
      WHEN LENGTH < 10 THEN 10
      ELSE LENGTH
    END AS LENGTH
  FROM FISH_INFO
) f
GROUP BY
  f.FISH_TYPE
HAVING
  AVG(f.LENGTH) >= 33
ORDER BY
  f.FISH_TYPE;
